### ISSUE TITLE
'Heron.gui.settings' has no attribute 'settings_dict' on windows with pip install

### ISSUE THREAD

**Issue by Iceweasle** [Heron-Repositories/Heron#27] opened 2024-07-04 00:16 UTC
Hi there,
I am very interested in using this framework. I am having a couple of issues. This issue is related to the pip install on a windows 10 machine. I am finding that the paramiko client fails when the settings_dict attribute is not getting set. Is there an easy fix for this? 

> \anaconda3\envs\NewPipHeron\Lib\site-packages\Heron\communication\sink_worker.py", line 206, in heartbeat_loop
    heartbeat_rate = settings.settings_dict['Operation']['HEARTBEAT_RATE']
                     ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'Heron.gui.settings' has no attribute 'settings_dict'

**Comment by georgedimitriadis** [comment] 2024-07-04 09:18
Hi Iceweasle.

Thanks for the bug report. Try again (pip uninstall the old Heron and re install). The new version should have no problems with the settings. Let me know if it is ok and I will close the issue, otherwise I will have another look at it.

**Comment by georgedimitriadis** [comment] 2024-07-04 11:31
Also, forgot to mention. pip uninstall will leave behind the Heron folder which needs deleting before reinstalling.

**Comment by georgedimitriadis** [comment] 2024-08-22 12:22
I am closing this now since I asume the problem is fixed.

**Closed as completed by georgedimitriadis** 2024-08-22 12:22 UTC
